---
- hosts: all
  vars:
    - gitlab_url: http://vagranthost
    - yum_repo_url: https://packages.gitlab.com/gitlab/gitlab-ee/el/7/$basearch
  tasks:
    - name: Add the yum repo
      yum_repository:
        name: gitlab
        description: Gitlab repository
        baseurl: "{{ yum_repo_url }}"
      become: yes
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - policycoreutils-python
        - openssh-server
      become: yes

    - name: Enable required services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - sshd
      become: yes


    - name: Allow ports through the firewall
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - ssh
        - http
      become: yes
      notify: restart firewalld

    - name: Install gitlab
      yum:
        name: gitlab-ee
        state: present
      become: yes
      environment:
        - EXTERNAL_URL: "{{ gitlab_url }}"

  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
      become: yes
