---
- hosts: all
  vars:
    yum_repo_url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/config_file.repo?os=${os}&dist=${dist}&source=script
  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - policycoreutils-python
        - openssh-server
      become: yes

    - name: Enable required services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - sshd
      become: yes

    - name: Allow ports through the firewall
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - ssh
        - http
      become: yes
      notify: restart firewalld

  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
      become: yes
