---
- hosts: all
  vars:
    - gitlab_url: http://vagranthost
  tasks:
    - name: Install default gpg keys
      rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        - /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        - /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Debug-7
        - /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Testing-7
      become: yes

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - policycoreutils-python
        - openssh-server
      become: yes

    - name: Enable required services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - sshd
      become: yes


    - name: Allow ports through the firewall
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - ssh
        - http
      become: yes
      notify: restart firewalld

    - name: Copy official install script
      copy:
        src: script.rpm.sh
        dest: /tmp/script.rpm.sh

    - name: Install gitlab using official shell script
      command: sh /tmp/script.rpm.sh
      args:
        creates: /etc/yum.repos.d/gitlab_gitlab-ee.repo
      become: yes

    - name: Install gitlab
      yum:
        name: gitlab-ee
        state: present
      become: yes
      environment:
        EXTERNAL_URL: http://vagranthost

  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
      become: yes
